### ISSUE TITLE
Desktop items not clickable at 'show desktop'

### ISSUE THREAD

**Issue by jg22** [dannystewart/volumeHUD#16]
There is a strange bug while running this app that also seems to affect other volume related apps too. When I do 'show desktop', non of the desktop icons are clickable, if I quit the app, the icons on the desktop are clickable again.

By 'show desktop', I mean the gesture (four fingers pinch out on the trackpad) that temporarily move all the windows away and reveal the desktop.

See the description of show desktop here
https://discussions.apple.com/thread/255875028?sortBy=rank

**Comment by dannystewart** [comment]
Hello! This was also [reported](https://github.com/dannystewart/volumeHUD/issues/6) as a bug earlier, and I implemented a fix, but based on this it seems like it didn't work. This happens because the volume UI needs to appear above all other windows and display elements, but by doing that, it competes with Exposé when it's trying to do the same thing. This is a tricky one. You noted that it affects other volume-related apps too, which implies this may be a problem without a straightforward solution, but I'll see if I can come up with something more robust.

**Comment by dannystewart** [comment]
Thank you, I really appreciate the understanding and patience. I'm glad to hear that at least brightness is fixed! Give me a little time to do some more research and testing. I'll do my best to see if I can reproduce the issue and find a fix for you.

**Comment by jg22** [comment]
@dannystewart Hi! Thank you for letting me know, I tried it out just now, still doesn't fix it I'm afraid.

**Comment by dannystewart** [comment]
Brilliant find! I will test this out shortly and if all goes well I will try to push an update later today. Thank you!

**Comment by dannystewart** [comment]
[Version 3.2.0](https://github.com/dannystewart/volumeHUD/releases/tag/v3.2.0) is now up with this (hopefully) fixed once and for all. Thank you so much @usagimaru for the fix and @jg22 for your patience and understanding. I really appreciate it.
